### ISSUE TITLE
Not an issue more of a request 

### ISSUE THREAD

**Issue by konqiko** [zhujunsan/p3-lte#1]
Will you bring this to gpd win 3? I would pay you for this and install myself if you gave me instructions ? I spoke to gpd and they sent me to you after seeing them sharing your links on Facebook

**Comment by zhujunsan** [comment]
I've only got a GPD Pocket 3 and this module is specifically designed for that. And I don't think gpd win 3 has a slot which can install a module. if you wanna do this, it might require a lot ingenuity : )

you can check all the hardware design in the repo, and i'm happy to help if you need anything.
