### ISSUE TITLE
Add the files needed to create the PCB

### ISSUE THREAD

**Issue by rina2016** [zhujunsan/p3-lte#3]
I would like to make this module, but could you upload a file in the following format required to request the production of the board?

pcb:connector LTE_module

pcbname.GTL Surface copper foil
pcbname.GTS Surface solder mask
pcbname.GTO surface silk printing
pcbname.GBL Back side copper foil
pcbname.GBS Back side solder mask
pcbname.GBO Backside silk printing
pcbname.TXT drill
pcbname.GML / GKO Board outline
pcbname.GL2 Internal layer 2 (in the case of 4 or more layers)
pcbname.GL3 Internal layer 3 (in the case of 4 or more layers)

**Comment by zhujunsan** [comment]
files' been added in hardware folder as in 63aec99468fc72840a0a33c69ef2079c0c2bac85
