### ISSUE TITLE
I want you to add the data necessary for mounting the parts of the PCB.

### ISSUE THREAD

**Issue by rina2016** [zhujunsan/p3-lte#4]
I would like to request the mounting of parts when manufacturing the board, so I would like you to add files such as coordinate data necessary for mounting the parts.

**Comment by rina2016** [comment]
I need the coordinate data to attach the parts, can I output it?
[座標データの例.txt](https://github.com/zhujunsan/p3-lte/files/8803004/default.txt)

**Comment by rina2016** [comment]
I need the coordinate data to attach the parts, can I output it
[layout.txt](https://github.com/zhujunsan/p3-lte/files/8803009/layout.txt)
?

**Comment by rina2016** [comment]
I need the coordinate data to attach the parts, can you output it?
example file:

[layout.txt](https://github.com/zhujunsan/p3-lte/files/8809668/layout.txt)

**Comment by zhujunsan** [comment]
I'm new to pcb design so tell me if i'm wrong. the following files are the maybe modified version gerber files and coordinates file

[Gerber_PCB_P3 Lte_2022_06_03.zip](https://github.com/zhujunsan/p3-lte/files/8832206/Gerber_PCB_P3.Lte_2022_06_03.zip)

[PickAndPlace_PCB_P3 Lte_2022-06-03.csv](https://github.com/zhujunsan/p3-lte/files/8832204/PickAndPlace_PCB_P3.Lte_2022-06-03.csv)
