### ISSUE TITLE
我想知道连接器的探针间距是多少

### ISSUE THREAD

**Issue by MengYang37** [zhujunsan/p3-lte#5]
我想知道连接器的探针间距是多少，方便我采购

**Comment by zhujunsan** [comment]
我用手测量的是1.8mm，所以这么设计了。因为只用了四个触点，所以略有一点误差应该也问题不太大
淘宝上我找过问过了没有现成的4个一起的元件，只能一个个自己搞。
然后记得要买加细的，加细的直径1mm，默认的直径1.5。以及不要底下焊盘的，加细的1mm，焊盘1.5mm，间距太小了不太好搞

**Comment by zhujunsan** [comment]
如果你有找到现成4个一体的那种还烦请分享一下哈

**Comment by MengYang37** [comment]
我找到的最小间距的是1.9mm的4P

**Comment by MengYang37** [comment]
我准备把16个脚全引出来，两个USB2.0，一个USB3.0，我手动测量应该在1.6左右，但我没找到一体的

**Comment by MengYang37** [comment]
https://item.taobao.com/item.htm?_u=81s8tbde106d&id=668109629278

**Comment by zhujunsan** [comment]
> 我准备把16个脚全引出来，两个USB2.0，一个USB3.0，我手动测量应该在1.6左右，但我没找到一体的

你如果要16个pin全引出的话精度要求更高了就...

**Comment by zhujunsan** [comment]
> https://item.taobao.com/item.htm?_u=81s8tbde106d&id=668109629278

哟感谢，我去买来试一下尺寸

**Comment by MengYang37** [comment]
![image](https://user-images.githubusercontent.com/52416684/183839625-5aac60fc-0532-4543-9d4c-add4adead77b.png)
这是我昨晚一边画一遍打印比划得到的相对吻合的间距

**Comment by MengYang37** [comment]
![image](https://user-images.githubusercontent.com/52416684/183932431-341a9360-a9a0-423e-9460-69dfa6788fcd.png)
实际画的图

**Comment by zhujunsan** [comment]
![PXL_20220810_132231661](https://user-images.githubusercontent.com/839807/184047225-c38fe15f-47f3-4932-acde-e0a92932f40c.jpg)

**Comment by MengYang37** [comment]
能请你帮忙测试一下这个接口吗，我这边测试这个接口无法识别USB3.0

**Comment by zhujunsan** [comment]
> 能请你帮忙测试一下这个接口吗，我这边测试这个接口无法识别USB3.0

我好像暂时没法引出来全部的触点，不过自带的模块就是转3.0A口呀。你那边有模块么？

**Comment by MengYang37** [comment]
我就是用自带的模块测的，虽然是3.0的口，并且全部引出，但3.0U盘插上去识别出来的是2.0，其他两个USB3.0口可正常识别

**Comment by MengYang37** [comment]
我想扔一个5G模块进去，需要USB3.0接口

**Comment by zhujunsan** [comment]
> 我就是用自带的模块测的，虽然是3.0的口，并且全部引出，但3.0U盘插上去识别出来的是2.0，其他两个USB3.0口可正常识别

这个我没问题，可以识别 3.0。这个口的 3.0 是 Gen1 的，5Gbps 的速度。另两个侧面的口是 Gen2 的

**Comment by zhujunsan** [comment]
> 我想扔一个5G模块进去，需要USB3.0接口

哈哈哈你能找到能塞得进去的 5G 模块么？感觉尺寸上完全不行，整个塞进去的模块厚度大概只能 3mm 多一点，大小也比较小，天线也不好搞

**Comment by MengYang37** [comment]
这不就是盯上了电脑的5G网卡，3042的尺寸，挤挤勉强放得下，得研究3.0的接线
